// Generated by Selenium IDE
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using Xunit;
public class SuiteTests : IDisposable {
  public IWebDriver driver {get; private set;}
  public IDictionary<String, Object> vars {get; private set;}
  public IJavaScriptExecutor js {get; private set;}
  public SuiteTests()
  {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<String, Object>();
  }
  public void Dispose()
  {
    driver.Quit();
  }
  [Fact]
  public void Hello() {
    driver.Navigate().GoToUrl("https://safatelli.github.io/tp-test-logiciel/assets/hello.html");
    driver.Manage().Window.Size = new System.Drawing.Size(1296, 688);
    driver.FindElement(By.Id("username")).Click();
    driver.FindElement(By.Id("username")).SendKeys("Omar");
    driver.FindElement(By.CssSelector("button")).Click();
    driver.FindElement(By.CssSelector("body")).Click();
    driver.FindElement(By.Id("username")).SendKeys("Arij");
    driver.FindElement(By.CssSelector("button")).Click();
    driver.FindElement(By.CssSelector("html")).Click();
  }
}
